name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: my-devops-app
  REGISTRY: ghcr.io
  VERSION: v${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
         image: sonarqube:lts-community
         ports:
          - 9000:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run API tests
        run: npm test --if-present

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: http://sonarqube:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:$VERSION .
          docker tag $REGISTRY/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:$VERSION \
                     $REGISTRY/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:latest

      - name: Login to GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push to GHCR
        run: |
          docker push $REGISTRY/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:$VERSION
          docker push $REGISTRY/${{ secrets.GHCR_USERNAME }}/$IMAGE_NAME:latest

      - name: Upload manifest for CD
        uses: actions/upload-artifact@v4
        with:
          name: k8s-manifests
          path: k8s/
